Send Request
GET http://localhost:3000/movies/

GET http://localhost:3000/movies/49/


GET http://localhost:3000/directors/


POST http://localhost:3000/movies
Content-Type: application/json

{
    "directorId":85,
    "movieName":"ABHI",
    "leadActor":"Ram"
}


DELETE http://localhost:3000/movies/50